### ISSUE TITLE
Four digit year

### ISSUE THREAD

**Issue by briandickens** [tc60045/scoutbook_parsing#1]
All the scripts requiring a date input fail if you provide a four digit year. 

Maybe try something like this?

```
# using try-except blocks for handling the exceptions
try:

   # formatting the date using strptime() function
   dateObject = datetime.datetime.strptime(date_string, date_format)
   print(dateObject)

# If the date validation goes wrong
except ValueError:

   # printing the appropriate text if ValueError occurs
   print("Incorrect data format, should be MM/DD/YY")
```

**Comment by tc60045** [comment]
Nope, they require a two digit date, as in 01/01/23, and I will keep it that way.

Share the output of your error(s).  Thx

**Comment by briandickens** [comment]
Output:
`PS D:\ScoutbookParsing> python.exe .\mbs_since.py .\ReportBuilder_troop_merit_badge_dump_20230817.csv 06/01/2023
Traceback (most recent call last):
  File "D:\ScoutbookParsing\mbs_since.py", line 63, in <module>
    main()
  File "D:\ScoutbookParsing\mbs_since.py", line 47, in main
    scout_data = parse_csv(filename, eval_date)
  File "D:\ScoutbookParsing\mbs_since.py", line 13, in parse_csv
    eval_date = datetime.strptime(eval_date, '%m/%d/%y')
  File "C:\Users\brian\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\brian\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 23`

Maybe returning date formatting instructions here would be good.

**Comment by tc60045** [comment]
Well you entered a four digit year and it threw an error.  Enter a two-digit year. 

I show the command for each utility in the sample output, figuring that Scouts (a) want to know precisely what they will get and (b) are resourceful and would look there for command convention.  For mbs_since.py the command is (Linux / MacOS)


python3 mbs_since.py filename.csv 06/01/23

**Comment by tc60045** [comment]
Thx for closing out / hope it works as expected. 

I updated the Readme with a shout-out to you and explicit confirmation of the convention. 

I’m working on parsing rank records right now, all 200+ columns, so back to that salt mine….
